## this is sh for resources/svg
touch svg.gen
echo "################svg.gen###################"> svg.gen 
echo "#     AUTO GENERATED BY res.sh         #">> svg.gen
echo "#######################################">> svg.gen
touch svg.utils
mkdir svg
for files in *.svg
do
  echo "svg/$files">> svg.gen
  echo "svg/$files">> svg.utils
  mv $files svg
done

